### ISSUE TITLE
wrong debug message?

### ISSUE THREAD

**Issue by XSven** [briandfoy/test-manifest#15]
I don't understand the debug message [L226](https://metacpan.org/dist/Test-Manifest/source/lib/Test/Manifest.pm#L226)

> Test::Manifest::test_harness found [@files]\n

`Test::Manifest` has no function/method with the name `test_harness`?! `test_harness` belongs to `ExtUtils::Command::MM` and it is used to run the tests if `Test::Manifest` isn't active.

**Comment by briandfoy** [comment]
Fixed, thanks.
